# config.py
EMAIL = "roskiit@usc.edu"
PASSWORD = "xnd8aej7khp*CTP5dpb"
WUFOO_LOGIN_URL = "https://secure.wufoo.com/login/"
WUFOO_SOURCE_PATH = "/Users/rad_it/Downloads/adobe-creative-cloud-access-spring-2025_entries.csv"
WUFOO_DST_PATH = "/Users/rad_it/Desktop/adobe-lisence-approver-automation/adobe-creative-cloud-access-spring-2025_entries.csv"
SEARCH_BAR_INPUT = "ADOBE CREATIVE CLOUD ACCESS SPRING 2025"
ADOBE_URL ="https://www.adobe.com/"
USC_ID = "roskiit"
USC_PWD = "YXN!phj4hyc*urf7zmz"